"""
Django settings for unihaven_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-pr!^&c=(!w^j3!fnlo3l75*s3wgh*0+9$=vdbfagzdxb$bu46!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreplyhku0@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'tkyb kieb pbzv comw'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'noreplyhku0@gmail.com'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api.apps.ApiConfig",
    "rest_framework",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'api.middleware.UniversityAuthenticationMiddleware',
]

ROOT_URLCONF = "unihaven_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "unihaven_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# University API Keys (move to environment variables in production)
UNIVERSITY_API_KEYS = {
    'HKU': 'hku-secret-key-2025',
    'HKUST': 'hkust-secret-key-2025',
    'CUHK': 'cuhk-secret-key-2025'
}

# Add to REST_FRAMEWORK settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.UniversityAPIKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'api.permissions.IsUniversitySystemAuthenticated',
    ],
}

# Add Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'UniHaven API',
    'DESCRIPTION': '''
    API for managing student accommodations across universities.
    
    Authentication:
    - Use X-University-API-Key header with your university's API key
    - Example: X-University-API-Key: hku-secret-key-2025
    
    Available API Keys for Testing:
    - HKU: hku-secret-key-2025
    - HKUST: hkust-secret-key-2025
    - CUHK: cuhk-secret-key-2025
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelRendering': 'model',
        'defaultModelsExpandDepth': -1,
        'defaultModelExpandDepth': 3,
        'showExtensions': True,
        'showCommonExtensions': True,
        'supportedSubmitMethods': ['get', 'post', 'put', 'delete', 'patch'],
        'tryItOutEnabled': True,  # Enable try it out by default
        'displayRequestDuration': True,
        'filter': True,
        'requestSnippetsEnabled': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SERVE_INCLUDE_SCHEMA': True,
    'SERVE_PUBLIC': True,
    'TAGS': [
        {'name': 'Search', 'description': 'Search functionality for accommodations'},
        {'name': 'accommodations', 'description': 'Accommodation management endpoints'},
        {'name': 'students', 'description': 'Student registration and management'},
        {'name': 'specialists', 'description': 'Accommodation specialist management'},
        {'name': 'reservations', 'description': 'Manage accommodation reservations'},
        {'name': 'ratings', 'description': 'Rate and review accommodations'}
    ],
    'SECURITY': [{'University-API-Key': []}],
    'SCHEMA_PATH_PREFIX': '/api/',
    'ENUM_NAME_OVERRIDES': {
        'TypeEnum': 'api.models.Accommodation.ACCOMMODATION_TYPES'
    }
}
